source $HOME/.cargo/env
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias vim=`which nvim`
export EDITOR=vim
export JAVA_HOME=jdk-17.0.5+8
eval "$(direnv hook zsh)"
eval "$(starship init zsh)"

export PATH=$PATH:$JAVA_HOME/bin:/usr/local/go/bin
