export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias vim=`which nvim`
export EDITOR=`which nvim`

source $HOME/.cargo/env
source /opt/tools/z/z.sh
source $HOME/.sdkman/bin/sdkman-init.sh

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
eval "$($HOME/.rbenv/bin/rbenv init - zsh)"

export PATH=$PATH:$JAVA_HOME/bin:/usr/local/go/bin
